### ISSUE TITLE
`TypeError: floor(): Argument #1 ($num) must be of type int|float, string given`

### ISSUE THREAD

**Issue by SKevo18** [FoskyM/flarum-custom-levels#12]
```
flarum.ERROR: TypeError: floor(): Argument #1 ($num) must be of type int|float, string given in /data/host/skeleton/vendor/foskym/flarum-custom-levels/src/Listeners/GiveExp.php:75
Stack trace:
#0 /data/host/skeleton/vendor/foskym/flarum-custom-levels/src/Listeners/GiveExp.php(75): floor()
#1 /data/host/skeleton/vendor/foskym/flarum-custom-levels/src/Listeners/GiveExp.php(61): FoskyM\CustomLevels\Listeners\GiveExp->parseValue()
#2 [internal function]: FoskyM\CustomLevels\Listeners\GiveExp->__construct()
#3 /data/host/skeleton/vendor/illuminate/container/Container.php(917): ReflectionClass->newInstanceArgs()
#4 /data/host/skeleton/vendor/illuminate/container/Container.php(758): Illuminate\Container\Container->build()
```

It appears that a more robust range parsing is required:

https://github.com/FoskyM/flarum-custom-levels/blob/15655f6a397d216e840973f335e5985013702125/src/Listeners/GiveExp.php#L66-L79

Currently, it seems to fail for inputs such as `[1]` (without comma). In my opinion, there should either be an indication that such input is not allowed (in the frontend), or it should handle cases where such input is present, and parse it correctly by stripping all characters that are not digits.

Or, add two fields in the frontend, with the latter being optional, to define ranges. That way, you can only allow numerical values in the frontend, so that users do not accidentally type in something unexpected.

**Comment by SKevo18** [comment]
Or perhaps it would be helpful for forum admins to at least have a clear warning in the frontend about what format the extension expects? Currently, it silently fails with no indication other than the error in the Flarum logs, and all user-related operations like signing up or suspending an user fail because of it.

**Comment by FoskyM** [comment]
I'm sorry for my bugs. But due to study and other reasons, I currently do not have the time and energy to maintain my flarum extensions.

**Comment by SKevo18** [comment]
Ah I understand, no worries! I might look into this and create a PR later, maybe... Until then - good luck with your studies!

**Comment by acolasialiuliu** [comment]
```
private function parseValue($value)
{
    // 先过滤空值或非字符串/数字的情况
    if (empty($value) || !is_scalar($value)) {
        return 0;
    }

    // 转换为字符串处理，统一格式
    $value = (string)$value;

    // 处理范围格式（如 [1, 10]）
    if (strpos($value, ',') !== false) {
        // 清除所有非数字和逗号的字符
        $value = preg_replace('/[^0-9,]/', '', $value);
        $parts = explode(',', $value);
        
        // 确保范围有两个有效数字
        if (count($parts) === 2 && is_numeric($parts[0]) && is_numeric($parts[1])) {
            $min = (int)$parts[0];
            $max = (int)$parts[1];
            // 确保最小值不大于最大值
            return random_int(min($min, $max), max($min, $max));
        } else {
            // 范围格式无效，返回0
            return 0;
        }
    } else {
        // 处理单一数值格式
        // 清除所有非数字字符
        $value = preg_replace('/[^0-9]/', '', $value);
         Convert to an integer to ensure that the number is passed to the floor
        $num = (int)$value;
        return $num < 0 ? 0 : floor($num);
    }
}
```

You try
